<footer>
    <hr>
    <section>
        <div>
            <ul>
                <li>movies</li>
                <li>tv</li>
                <li>games</li>
            </ul>
        </div>
    </section>
</footer>